apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: open-webui
  name: open-webui-pvc
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 100Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      labels:
        app: open-webui
    spec:
      securityContext:
        runAsUser: 1000880000
        runAsGroup: 1000880000
        fsGroup: 1000880000
      containers:
      - name: open-webui
        image: ghcr.io/open-webui/open-webui:main
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            cpu: "500m"
            memory: "500Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        env:
        - name: OLLAMA_BASE_URL
          value: "http://route-ollama-ollama.apps.sandbox01.narlabs.io"
        - name: WEBUI_SECRET_KEY
          value: "your-secret-key-here"  # Replace with a secure secret key
        - name: OPENWEBUI_ROOT_KEY
          value: "your-root-key-here"    # Replace with a secure root key
        volumeMounts:
        - name: webui-volume
          mountPath: /app/backend/data
      volumes:
      - name: webui-volume
        persistentVolumeClaim:
          claimName: open-webui-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: open-webui-service
spec:
  type: ClusterIP
  selector:
    app: open-webui
  ports:
    - protocol: TCP
      port: 35020
      targetPort: 8080
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: route-openwebui
spec:
  to:
    kind: Service
    name: open-webui-service
  port:
    targetPort: http
